name:        simple-vec3
version:     "0.2"
synopsis:    Three-dimensional vectors of doubles with basic operations

description: Simple three-dimensional vectors of doubles with basic
             vector and matrix operations, supporting
             "Data.Vector.Unboxed" and "Data.Vector.Storable".

github:      dzhus/simple-vec3
license:     BSD3
author:      Dmitry Dzhus
maintainer:  dima@dzhus.org
category:    Math, Numerical

ghc-options:
  - -Wall
  - -Wcompat
  - -O2

dependencies:
  - base < 5
  - QuickCheck
  - vector
  - vector-th-unbox

library:
  source-dirs: src
  other-modules:
    - Data.Vec3.Tupled

benchmarks:
  simple-vec3-benchmark:
    source-dirs: benchmark
    main: Benchmark.hs
    dependencies:
      - criterion
      - simple-vec3

tests:
  simple-vec3-test:
    source-dirs: tests
    main: Tests.hs
    dependencies:
      - simple-vec3
      - tasty
      - tasty-quickcheck
      - tasty-th
