name:        simple-vec3
version:     "0.4.0.6"
synopsis:    Three-dimensional vectors of doubles with basic operations

description: Simple three-dimensional vectors of doubles with basic
             vector and matrix operations, supporting
             "Data.Vector.Unboxed" and "Data.Vector.Storable".

github:      dzhus/simple-vec3
license:     BSD3
author:      Dmitry Dzhus
maintainer:  dima@dzhus.org
category:    Math, Numerical

extra-source-files:
  - CHANGELOG.md
  - README.md

ghc-options:
  - -Wall
  - -Wcompat
  - -O2

dependencies:
  - base < 5

library:
  source-dirs: src
  dependencies:
    - QuickCheck
    - vector

benchmarks:
  simple-vec3-benchmark:
    source-dirs: benchmark
    main: Benchmark.hs
    dependencies:
      - criterion
      - simple-vec3
      - vector

tests:
  simple-vec3-test:
    source-dirs: tests
    main: Main.hs
    dependencies:
      - simple-vec3
      - tasty
      - tasty-quickcheck

  simple-vec3-doctests:
    source-dirs: tests
    main: doctest-driver.hs
    ghc-options: -threaded
    dependencies:
      - doctest
      - doctest-driver-gen
